action: ['train','valid','test']  # one of [train, train+valid, train+test, valid, test]
seed: 0
cuda: 3
data:
  type: beta
  data_folder: data/FB15k-237-betae
  cpu: 10
train:
  negative_sample_size: 128  # for each positive sample
  batch_size: 512
  learning_rate: 0.0001
  steps: 50000
  log_every_steps: 100
  warm_up_steps: 25000
  evaluate_every_steps: 15000
  save_every_steps: 10000
  checkpoint_every: 10000
  meta_queries:
     - 1p
     - 2p
     - 3p
     - 2i
     - 3i
     - 2D
     - 3D
evaluate:  # only used when valid/test in action
  batch_size: 1000
  print: true
  meta_queries:
     - 1p
     - 2p
     - 3p
     - 2i
     - 3i
     - 2D
     - 3D
     - ip
     - pi
     - 2u-DNF
     - up-DNF
     - Dp
estimator:
  embedding: NewLook # one of [Transe, box, beta, dm]
  beta:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    # evaluate_union: DM # one of [DM, DNF] after parsing it can be omitted
    gamma: 60
  box:
    entity_dim: 400
    relation_dim: 400
    offset_activation: None
    center_reg: 0.02
    gamma: 60
  dm:
    entity_dim: 2
    relation_dim: 2
    hidden_dim: 1600
    num_layers: 2
  logic:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    num_layers: 2
    evaluate_union: DM
    gamma: 0.375
    t_norm: luk
    bounded: 1
    use_att: 1
    use_gtrans: 0
  cqd:
    entity_dim: 1000 # actually 2000
    relation_dim: 1000
    norm_type: product
  NewLook:
    entity_dim: 400
    relation_dim: 400
    hidden_dim: 1600
    center_reg: 0.2
    x_reg: 0.02 # \lambda in the paper
    gamma: 24
    group_number: 200

